version: '3.1'

services:
  dbRickAndMorty:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: rickandmorty_server
    ports:
      - 6543:6543
